test commit
madokasugita/ci-test-circle pull request #6
Opened 2016-12-13 06:10 UTC by ryomaruo182

test

2017-01-17 06:41 UTC, ryomaruo182 commented
このコメント欄見にくいな

2017-01-17 06:42 UTC, ryomaruo182 commented
プルリクの通知ってちゃんと行ってますか～

2017-01-17 06:42 UTC, ryomaruo182 commented
ｱｱｱｱｱｱｱｱｱｱｱｱｱｱｱｱｱｱｱｱｱｱｱｱ

2017-01-18 05:19 UTC, madokasugita commented
@ryomaruo182 暴れてるなｗメール来てました！

2017-01-18 06:36 UTC, madokasugita requested changes

2017-01-18 06:36 UTC, madokasugita commented on check_syntax.sh
> +        | xargs -I{} vendor/bin/phpmd {} text rules/phpmd_rules.xml \
ここに追加してもらっていますが、ここだとファイルではなくて引数としてphpcsの結果レポートが入ってきてしまうのでphpmdの分はphpcsとは分離して書くようにお願いしますー(*_ _)

2017-01-18 06:41 UTC, ryomaruo182 commented on check_syntax.sh
> +        | xargs -I{} vendor/bin/phpmd {} text rules/phpmd_rules.xml \
ありがとうございます。
そうですよね(~o~)
修正いたします。

2017-01-19 03:13 UTC, madokasugita commented on controllers/global.php
> +<?php
ERROR: Default timezone is required since PHP 5.4

2017-01-19 03:13 UTC, madokasugita commented on controllers/global.php
> +global $testXXX;
ERROR: Expected 1 blank line at end of file; 2 found

2017-01-19 07:37 UTC, madokasugita commented on controllers/global.php
> +<?php
ERROR: Default timezone is required since PHP 5.4

2017-01-19 08:27 UTC, madokasugita commented on controllers/global.php
> +echo "globalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalg
ERROR: Expected 1 newline at end of file; 0 found

2017-01-24 02:29 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $_POST['f'];
ERROR: Visibility must be declared on property "$_POST"

2017-01-24 02:29 UTC, madokasugita commented on core/ClassLoader.php
> +    $auto_q_no_params
ERROR: There must not be more than one property declared per statement

2017-01-24 02:29 UTC, madokasugita commented on core/ClassLoader.php
> +    $auto_q_no_params
ERROR: Visibility must be declared on property "$auto_q_no_params"

2017-01-24 02:29 UTC, madokasugita commented on core/Controller.php
> +    echo $_POST['f'];
ERROR: Visibility must be declared on property "$_POST"

2017-01-24 02:29 UTC, madokasugita commented on core/Controller.php
> +    $auto_q_no_params
ERROR: There must not be more than one property declared per statement

2017-01-24 02:29 UTC, madokasugita commented on core/Controller.php
> +    $auto_q_no_params
ERROR: Visibility must be declared on property "$auto_q_no_params"

2017-01-24 02:58 UTC, madokasugita commented on core/ClassLoader.php
> +    $auto_q_no_para
ERROR: There must not be more than one property declared per statement

2017-01-24 02:58 UTC, madokasugita commented on core/ClassLoader.php
> +    $auto_q_no_para
ERROR: Visibility must be declared on property "$auto_q_no_para"

2017-01-24 02:58 UTC, madokasugita commented on core/Controller.php
> +    $auto_q_no_
ERROR: There must not be more than one property declared per statement

2017-01-24 02:58 UTC, madokasugita commented on core/Controller.php
> +    $auto_q_no_
ERROR: Visibility must be declared on property "$auto_q_no_"

2017-01-26 07:02 UTC, madokasugita commented on core/Controller.php
> +    protected function checkCsrfToken($form_name, $token){
ERROR: Opening brace should be on a new line

2017-01-27 10:28 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variable
ERROR: There must not be more than one property declared per statement

2017-01-27 10:28 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variable
ERROR: Visibility must be declared on property "$miss_variable"

2017-01-27 10:28 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: There must not be more than one property declared per statement

2017-01-27 10:28 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: Visibility must be declared on property "$miss_variable2"

2017-02-16 09:37 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-16 09:37 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-16 09:37 UTC, madokasugita commented on core/Application.php
> +echo $miss_variable
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-16 09:37 UTC, madokasugita commented on core/Application.php
> +echo $miss_variable
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-16 09:37 UTC, madokasugita commented on phpmd_trans.php
> +<?php
ERROR: Default timezone is required since PHP 5.4

2017-02-16 09:41 UTC, madokasugita commented on core/Application.php
> +echo $miss_variable
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-16 09:45 UTC, madokasugita commented on core/Application.php
> +echo $miss_variable
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-16 09:48 UTC, madokasugita commented on core/Application.php
> +echo $miss_variable
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-20 06:18 UTC, madokasugita commented on core/Application.php
> +                            protected $db_manager;
ERROR: Line indented incorrectly; expected 4 spaces, found 28

2017-02-20 06:18 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 06:18 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 06:33 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 06:33 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 06:33 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: Unexpected token

2017-02-20 06:33 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: Unexpected token

2017-02-20 06:38 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 06:38 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 06:41 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 06:41 UTC, madokasugita commented on core/Application.php
> +    echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 06:52 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 06:52 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 06:52 UTC, madokasugita commented on core/Application.php
> +echo $miss_variablec
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-20 07:01 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 07:01 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 07:01 UTC, madokasugita commented on core/Application.php
> +echo $miss_variablec
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-20 07:01 UTC, madokasugita commented on phpmd_trans.php
> +                }
ERROR: Line indented incorrectly; expected 0 spaces, found 16

2017-02-20 07:01 UTC, madokasugita commented on phpmd_trans.php
> +                }
ERROR: Closing brace indented incorrectly; expected 0 spaces, found 16

2017-02-20 07:01 UTC, madokasugita commented on phpmd_trans.php
> +    if ($first_flg) {
ERROR: Line indented incorrectly; expected 0 spaces, found 4

2017-02-20 07:01 UTC, madokasugita commented on phpmd_trans.php
> +    }
ERROR: Line indented incorrectly; expected 0 spaces, found 4

2017-02-20 07:04 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 07:04 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 07:04 UTC, madokasugita commented on core/Application.php
> +echo $miss_variablec
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-20 07:04 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Unexpected token

2017-02-20 07:10 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 07:10 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 07:10 UTC, madokasugita commented on core/Application.php
> +echo $miss_variablec
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-20 07:10 UTC, madokasugita commented on core/ClassLoader.php
> +class ClassLoader
ERROR: Each class must be in a namespace of at least one level (a top-level vendor name)

2017-02-20 07:10 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: There must not be more than one property declared per statement

2017-02-20 07:10 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: Visibility must be declared on property "$miss_variable2"

2017-02-20 07:10 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Unexpected token: echo,

2017-02-20 07:22 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 07:22 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 07:22 UTC, madokasugita commented on core/Application.php
> +echo $miss_variablec
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-20 07:22 UTC, madokasugita commented on core/ClassLoader.php
> +class ClassLoader
ERROR: Each class must be in a namespace of at least one level (a top-level vendor name)

2017-02-20 07:22 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: There must not be more than one property declared per statement

2017-02-20 07:22 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: Visibility must be declared on property "$miss_variable2"

2017-02-20 07:22 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Unexpected token: echo,

2017-02-20 07:27 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 07:27 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 07:27 UTC, madokasugita commented on core/Application.php
> +echo $miss_variablec
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-20 07:27 UTC, madokasugita commented on core/ClassLoader.php
> +class ClassLoader
ERROR: Each class must be in a namespace of at least one level (a top-level vendor name)

2017-02-20 07:27 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: There must not be more than one property declared per statement

2017-02-20 07:27 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: Visibility must be declared on property "$miss_variable2"

2017-02-20 07:27 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Unexpected token: echo,

2017-02-20 07:29 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 07:29 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 07:29 UTC, madokasugita commented on core/Application.php
> +echo $miss_variablec
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-20 07:29 UTC, madokasugita commented on core/ClassLoader.php
> +class ClassLoader
ERROR: Each class must be in a namespace of at least one level (a top-level vendor name)

2017-02-20 07:29 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: There must not be more than one property declared per statement

2017-02-20 07:29 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: Visibility must be declared on property "$miss_variable2"

2017-02-20 07:29 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Unexpected token: echo,

2017-02-20 07:35 UTC, madokasugita commented on core/Application.php
> +abstract class Application
ERROR: Each class must be in a namespace of at least one level (a top-level vendor name)

2017-02-20 07:35 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 07:35 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 07:35 UTC, madokasugita commented on core/Application.php
> +echo $miss_variablec
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-20 07:35 UTC, madokasugita commented on core/ClassLoader.php
> +class ClassLoader
ERROR: Each class must be in a namespace of at least one level (a top-level vendor name)

2017-02-20 07:35 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: There must not be more than one property declared per statement

2017-02-20 07:35 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: Visibility must be declared on property "$miss_variable2"

2017-02-20 07:35 UTC, madokasugita commented on core/Application.php
> +abstract class Application
ERROR: Unexpected token: abstract,

2017-02-20 07:42 UTC, madokasugita commented on core/Application.php
> +abstract class Application
ERROR: Each class must be in a namespace of at least one level (a top-level vendor name)

2017-02-20 07:42 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: There must not be more than one property declared per statement

2017-02-20 07:42 UTC, madokasugita commented on core/Application.php
> +                        echo $miss_variablec
ERROR: Visibility must be declared on property "$miss_variablec"

2017-02-20 07:42 UTC, madokasugita commented on core/Application.php
> +echo $miss_variablec
ERROR: Line indented incorrectly; expected at least 4 spaces, found 0

2017-02-20 07:42 UTC, madokasugita commented on core/ClassLoader.php
> +class ClassLoader
ERROR: Each class must be in a namespace of at least one level (a top-level vendor name)

2017-02-20 07:42 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: There must not be more than one property declared per statement

2017-02-20 07:42 UTC, madokasugita commented on core/ClassLoader.php
> +    echo $miss_variable2
ERROR: Visibility must be declared on property "$miss_variable2"

2017-02-20 07:42 UTC, madokasugita commented on core/Application.php
> +abstract class Application
ERROR: Unexpected token: abstract

2017-03-02 02:22 UTC, madokasugita commented on controllers/global.php
> +<?php
ERROR: Default timezone is required since PHP 5.4

2017-03-02 02:22 UTC, madokasugita commented on controllers/global.php
> +echo "globalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalglobalg
ERROR: Expected 1 newline at end of file; 0 found

2017-03-02 02:22 UTC, madokasugita commented on core/Controller.php
> +    protected function checkCsrfToken($form_name, $token){
ERROR: Opening brace should be on a new line

2017-03-02 02:22 UTC, madokasugita commented on phpmd_trans.php
> +<?php
ERROR: Default timezone is required since PHP 5.4

2017-03-02 02:24 UTC, madokasugita approved these changes

2017-03-02 02:25 UTC, merged